import React, { useState } from 'react';
import { supabase, isSupabaseConfigured, updateSupabaseConfig } from '../lib/supabase';
import { Lock, Mail, ArrowRight, ShieldCheck, Database, AlertCircle, Key, Settings, Check } from 'lucide-react';

interface LoginModalProps {
  onLoginSuccess: (userEmail: string) => void;
  onBypassDemo: () => void;
}

export const LoginModal: React.FC<LoginModalProps> = ({ onLoginSuccess, onBypassDemo }) => {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [isSignUp, setIsSignUp] = useState(false);
  const [loading, setLoading] = useState(false);
  const [errorMsg, setErrorMsg] = useState<string | null>(null);
  const [showSqlModal, setShowSqlModal] = useState(false);
  const [showConfig, setShowConfig] = useState(!isSupabaseConfigured);

  // Supabase URL & Key inputs
  const [supabaseUrlInput, setSupabaseUrlInput] = useState(() => localStorage.getItem('supabase_url') || '');
  const [supabaseKeyInput, setSupabaseKeyInput] = useState(() => localStorage.getItem('supabase_anon_key') || '');
  const [configSaved, setConfigSaved] = useState(false);

  const handleSaveConfig = (e: React.FormEvent) => {
    e.preventDefault();
    if (!supabaseUrlInput.trim() || !supabaseKeyInput.trim()) {
      setErrorMsg('Supabase URL과 Anon Key를 모두 입력해주세요.');
      return;
    }
    updateSupabaseConfig(supabaseUrlInput, supabaseKeyInput);
    setConfigSaved(true);
    setErrorMsg(null);
    setTimeout(() => setConfigSaved(false), 3000);
  };

  const handleAuth = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!email || !password) {
      setErrorMsg('이메일과 비밀번호를 입력해주세요.');
      return;
    }

    if (!isSupabaseConfigured && !supabase) {
      // If not configured, use demo bypass
      onLoginSuccess(email);
      return;
    }

    setLoading(true);
    setErrorMsg(null);

    try {
      if (isSignUp) {
        const { data, error } = await supabase!.auth.signUp({
          email,
          password,
        });
        if (error) throw error;
        
        if (data.user) {
          await supabase!.from('login_logs').insert([
            { user_id: data.user.id, email: email, status: 'SIGNUP_SUCCESS' }
          ]);
        }
        alert('회원가입이 완료되었습니다. 로그인되었습니다.');
        onLoginSuccess(email);
      } else {
        const { data, error } = await supabase!.auth.signInWithPassword({
          email,
          password,
        });
        if (error) throw error;

        if (data.user) {
          await supabase!.from('login_logs').insert([
            { user_id: data.user.id, email: email, status: 'LOGIN_SUCCESS' }
          ]);
        }
        onLoginSuccess(email);
      }
    } catch (err: any) {
      setErrorMsg(err.message || '인증 처리 중 오류가 발생했습니다.');
    } finally {
      setLoading(false);
    }
  };

  const sqlScript = `-- 1. 로그인 기록 테이블 (Login Logs)
create table public.login_logs (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users(id) on delete set null,
  email text not null,
  logged_in_at timestamp with time zone default timezone('utc'::text, now()) not null,
  status text default 'SUCCESS'
);

-- 2. 구매 견적 및 CSV 누적 저장 테이블 (Purchase Quotes)
create table public.purchase_quotes (
  id bigint generated by default as identity primary key,
  quote_id text not null unique,
  pr_no text not null,
  item_code text not null,
  item_name text not null,
  supplier text not null,
  unit text not null,
  qty numeric not null,
  unit_price numeric,
  currency text default 'KRW',
  quote_date date,
  required_date date,
  promised_date date,
  status text default '견적',
  remark text,
  uploaded_by text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS 정책 설정
alter table public.login_logs enable row level security;
alter table public.purchase_quotes enable row level security;

create policy "Enable all access for authenticated users on login_logs" on public.login_logs
  for all using (auth.role() = 'authenticated');

create policy "Enable all access for authenticated users on purchase_quotes" on public.purchase_quotes
  for all using (auth.role() = 'authenticated');`;

  return (
    <div className="fixed inset-0 z-50 bg-slate-950/85 backdrop-blur-md flex items-center justify-center p-4 overflow-y-auto">
      <div className="bg-slate-900 border border-slate-800 rounded-3xl max-w-lg w-full p-8 shadow-2xl relative overflow-hidden text-slate-100 my-8">
        <div className="absolute top-0 right-0 w-64 h-64 bg-indigo-600/10 rounded-full blur-3xl pointer-events-none"></div>

        <div className="text-center mb-6 relative z-10">
          <div className="inline-flex items-center justify-center w-14 h-14 rounded-2xl bg-indigo-600/20 text-indigo-400 mb-4 border border-indigo-500/30 shadow-sm">
            <ShieldCheck className="w-7 h-7" />
          </div>
          <h2 className="text-2xl font-bold tracking-tight text-white">구매 견적 관리 시스템</h2>
          <p className="text-sm text-slate-400 mt-1.5">
            {isSupabaseConfigured 
              ? '🟢 Supabase 연결됨 (인증 및 DB 누적 저장 활성화)' 
              : '🟡 Supabase 미연결 (아래에서 설정하거나 데모로 시작)'}
          </p>
        </div>

        {/* Supabase Configuration Section */}
        <div className="mb-6 bg-slate-800/60 border border-slate-700/80 rounded-2xl p-4 relative z-10">
          <div className="flex items-center justify-between mb-2">
            <button
              type="button"
              onClick={() => setShowConfig(!showConfig)}
              className="flex items-center gap-2 text-xs font-semibold text-indigo-300 hover:text-indigo-200 cursor-pointer"
            >
              <Settings className="w-4 h-4" />
              <span>{showConfig ? 'Supabase 설정 접기' : '⚙️ Supabase 프로젝트 설정 (URL / Key 입력)'}</span>
            </button>
            <span className={`text-[10px] px-2 py-0.5 rounded-full ${isSupabaseConfigured ? 'bg-emerald-500/20 text-emerald-300 border border-emerald-500/30' : 'bg-amber-500/20 text-amber-300 border border-amber-500/30'}`}>
              {isSupabaseConfigured ? '연결됨' : '설정 필요'}
            </span>
          </div>

          {showConfig && (
            <form onSubmit={handleSaveConfig} className="space-y-3 mt-3 pt-3 border-t border-slate-700">
              <div>
                <label className="block text-[11px] font-medium text-slate-300 mb-1">Supabase Project URL</label>
                <input
                  type="text"
                  value={supabaseUrlInput}
                  onChange={e => setSupabaseUrlInput(e.target.value)}
                  placeholder="https://xyzproject.supabase.co"
                  className="w-full px-3 py-2 bg-slate-900 border border-slate-700 rounded-xl text-xs text-white placeholder-slate-500 focus:outline-hidden focus:ring-2 focus:ring-indigo-500/40"
                />
              </div>
              <div>
                <label className="block text-[11px] font-medium text-slate-300 mb-1">Supabase Anon Key (Public API Key)</label>
                <input
                  type="password"
                  value={supabaseKeyInput}
                  onChange={e => setSupabaseKeyInput(e.target.value)}
                  placeholder="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                  className="w-full px-3 py-2 bg-slate-900 border border-slate-700 rounded-xl text-xs text-white placeholder-slate-500 focus:outline-hidden focus:ring-2 focus:ring-indigo-500/40"
                />
              </div>
              <div className="flex items-center justify-between pt-1">
                <button
                  type="submit"
                  className="px-4 py-2 bg-indigo-600 hover:bg-indigo-700 text-white rounded-xl text-xs font-semibold cursor-pointer shadow-md transition-all flex items-center gap-1.5"
                >
                  {configSaved && <Check className="w-3.5 h-3.5 text-emerald-300" />}
                  설정 저장 및 연결
                </button>
                <button
                  type="button"
                  onClick={() => setShowSqlModal(true)}
                  className="text-xs text-indigo-400 hover:text-indigo-300 flex items-center gap-1 cursor-pointer underline"
                >
                  <Database className="w-3.5 h-3.5" /> SQL 스크립트 보기
                </button>
              </div>
            </form>
          )}
        </div>

        {errorMsg && (
          <div className="mb-5 p-3.5 bg-rose-500/10 border border-rose-500/30 text-rose-300 rounded-2xl text-xs flex items-center gap-2 relative z-10">
            <AlertCircle className="w-4 h-4 shrink-0 text-rose-400" />
            <span>{errorMsg}</span>
          </div>
        )}

        <form onSubmit={handleAuth} className="space-y-4 relative z-10">
          <div>
            <label className="block text-xs font-semibold text-slate-300 mb-1.5">업무용 이메일</label>
            <div className="relative">
              <Mail className="absolute left-3.5 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-500" />
              <input
                type="email"
                required
                value={email}
                onChange={e => setEmail(e.target.value)}
                placeholder="purchaser@company.com"
                className="w-full pl-10 pr-4 py-3 bg-slate-800/80 border border-slate-700 rounded-xl text-sm text-white placeholder-slate-500 focus:outline-hidden focus:ring-2 focus:ring-indigo-500/40 focus:border-indigo-500"
              />
            </div>
          </div>

          <div>
            <label className="block text-xs font-semibold text-slate-300 mb-1.5">비밀번호</label>
            <div className="relative">
              <Lock className="absolute left-3.5 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-500" />
              <input
                type="password"
                required
                value={password}
                onChange={e => setPassword(e.target.value)}
                placeholder="••••••••"
                className="w-full pl-10 pr-4 py-3 bg-slate-800/80 border border-slate-700 rounded-xl text-sm text-white placeholder-slate-500 focus:outline-hidden focus:ring-2 focus:ring-indigo-500/40 focus:border-indigo-500"
              />
            </div>
          </div>

          <button
            type="submit"
            disabled={loading}
            className="w-full py-3.5 px-4 bg-indigo-600 hover:bg-indigo-700 text-white font-semibold rounded-xl shadow-lg shadow-indigo-600/30 transition-all flex items-center justify-center gap-2 cursor-pointer disabled:opacity-50 mt-2"
          >
            {loading ? '처리 중...' : isSignUp ? '회원가입 및 로그인' : isSupabaseConfigured ? 'Supabase 로그인' : '로그인 (데모/인증 확인)'}
            <ArrowRight className="w-4 h-4" />
          </button>
        </form>

        <div className="mt-5 flex items-center justify-between text-xs text-slate-400 relative z-10">
          <button
            type="button"
            onClick={() => setIsSignUp(!isSignUp)}
            className="hover:text-indigo-400 underline cursor-pointer"
          >
            {isSignUp ? '이미 계정이 있으신가요? 로그인' : '계정이 없으신가요? 회원가입'}
          </button>
          
          <button
            type="button"
            onClick={() => setShowSqlModal(true)}
            className="flex items-center gap-1 text-indigo-400 hover:text-indigo-300 font-medium cursor-pointer"
          >
            <Database className="w-3.5 h-3.5" /> Supabase SQL 보기
          </button>
        </div>

        <div className="mt-6 pt-5 border-t border-slate-800 text-center relative z-10">
          <button
            type="button"
            onClick={onBypassDemo}
            className="text-xs text-slate-400 hover:text-slate-200 underline cursor-pointer font-medium"
          >
            데모 계정으로 바로 시작하기 (건너뛰기)
          </button>
        </div>
      </div>

      {showSqlModal && (
        <div className="fixed inset-0 z-60 bg-slate-950/90 flex items-center justify-center p-4">
          <div className="bg-slate-900 border border-slate-800 rounded-3xl max-w-2xl w-full p-6 shadow-2xl flex flex-col max-h-[85vh]">
            <div className="flex items-center justify-between mb-4">
              <div className="flex items-center gap-2">
                <Key className="w-5 h-5 text-indigo-400" />
                <h3 className="text-base font-bold text-white">Supabase DB 초기화 SQL 스크립트</h3>
              </div>
              <button
                onClick={() => setShowSqlModal(false)}
                className="text-slate-400 hover:text-white text-sm px-3 py-1 bg-slate-800 rounded-lg cursor-pointer"
              >
                닫기
              </button>
            </div>
            <p className="text-xs text-slate-400 mb-3">
              Supabase SQL Editor에 아래 스크립트를 실행하여 <code className="text-indigo-300">login_logs</code>와 <code className="text-indigo-300">purchase_quotes</code> 테이블을 생성하세요.
            </p>
            <textarea
              readOnly
              value={sqlScript}
              rows={16}
              className="w-full font-mono text-xs p-3.5 bg-slate-950 border border-slate-800 rounded-xl text-indigo-200 focus:outline-hidden"
            />
            <div className="mt-4 flex justify-end">
              <button
                onClick={() => {
                  navigator.clipboard.writeText(sqlScript);
                  alert('SQL 스크립트가 클립보드에 복사되었습니다.');
                }}
                className="px-4 py-2 bg-indigo-600 hover:bg-indigo-700 text-white rounded-xl text-xs font-semibold cursor-pointer"
              >
                클립보드 복사
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
